// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ChatSource } from "./ChatSource";
import type { ChatStatus } from "./ChatStatus";
import type { GitInfo } from "./GitInfo";
import type { Interaction } from "./Interaction";
import type { SessionSource } from "./SessionSource";

export type Chat = { id: string,
/**
 * Session id shared by threads that belong to the same session tree.
 */
sessionId: string,
/**
 * Source chat id when this chat was created by forking another chat.
 */
forkedFromId: string | null,
/**
 * The ID of the parent chat. This will only be set if this chat is a subagent.
 */
parentChatId: string | null,
/**
 * Usually the first user message in the chat, if available.
 */
preview: string,
/**
 * Whether the chat is ephemeral and should not be materialized on disk.
 */
ephemeral: boolean,
/**
 * Model provider used for this chat (for example, 'openai').
 */
modelProvider: string,
/**
 * Unix timestamp (in seconds) when the chat was created.
 */
createdAt: number,
/**
 * Unix timestamp (in seconds) when the chat was last updated.
 */
updatedAt: number,
/**
 * Unix timestamp (in seconds) used for chat recency ordering.
 */
recencyAt: number | null,
/**
 * Current runtime status for the chat.
 */
status: ChatStatus,
/**
 * [UNSTABLE] Path to the chat on disk.
 */
path: string | null,
/**
 * Working directory captured for the chat.
 */
cwd: AbsolutePathBuf,
/**
 * Version of the CLI that created the chat.
 */
cliVersion: string,
/**
 * Origin of the chat (CLI, VSCode, codex exec, codex app-server, etc.).
 */
source: SessionSource,
/**
 * Optional analytics source classification for this chat.
 */
chatSource: ChatSource | null,
/**
 * Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
 */
agentNickname: string | null,
/**
 * Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
 */
agentRole: string | null,
/**
 * Optional Git metadata captured when the chat was created.
 */
gitInfo: GitInfo | null,
/**
 * Optional user-facing chat title.
 */
name: string | null,
/**
 * Only populated on `chat/resume`, `chat/rollback`, `chat/fork`, and `chat/read`
 * (when `includeInteractions` is true) responses.
 * For all other responses and notifications returning a Chat,
 * the interactions field will be an empty list.
 */
interactions: Array<Interaction>, };
