// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatRollbackParams = { chatId: string,
/**
 * The number of interactions to drop from the end of the chat. Must be >= 1.
 *
 * This only modifies the chat.s history and does not revert local file changes
 * that have been made by the agent. Clients are responsible for reverting these changes.
 */
numInteractions: number, };
