// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - emitted when thread realtime encounters an error.
 */
export type ChatRealtimeErrorNotification = { chatId: string, message: string, };
