// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatStatus } from "./ChatStatus";

export type ChatStatusChangedNotification = { chatId: string, status: ChatStatus, };
