// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMetadataGitInfoUpdateParams } from "./ChatMetadataGitInfoUpdateParams";

export type ChatMetadataUpdateParams = { chatId: string,
/**
 * Patch the stored Git metadata for this chat.
 * Omit a field to leave it unchanged, set it to `null` to clear it, or
 * provide a string to replace the stored value.
 */
gitInfo?: ChatMetadataGitInfoUpdateParams | null, };
