// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeConversationVersion } from "../RealtimeConversationVersion";

/**
 * EXPERIMENTAL - emitted when chat realtime startup is accepted.
 */
export type ChatRealtimeStartedNotification = { chatId: string, realtimeSessionId: string | null, version: RealtimeConversationVersion, };
