// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRealtimeAudioChunk } from "./ChatRealtimeAudioChunk";

/**
 * EXPERIMENTAL - streamed output audio emitted by chat realtime.
 */
export type ChatRealtimeOutputAudioDeltaNotification = { chatId: string, audio: ChatRealtimeAudioChunk, };
