// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionError } from "./InteractionError";

export type ErrorNotification = { error: InteractionError, willRetry: boolean, chatId: string, interactionId: string, };
