// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuardianWarningNotification = {
/**
 * Chat target for the guardian warning.
 */
chatId: string,
/**
 * Concise guardian warning message for the user.
 */
message: string, };
