// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionError } from "./InteractionError";
import type { InteractionMessagesView } from "./InteractionMessagesView";
import type { InteractionStatus } from "./InteractionStatus";
import type { Message } from "./Message";

export type Interaction = { id: string,
/**
 * Chat messages currently included in this interaction payload.
 */
messages: Array<Message>,
/**
 * Describes how much of `messages` has been loaded for this interaction.
 */
messagesView: InteractionMessagesView, status: InteractionStatus,
/**
 * Only populated when the Interaction's status is failed.
 */
error: InteractionError | null,
/**
 * Unix timestamp (in seconds) when the interaction started.
 */
startedAt: number | null,
/**
 * Unix timestamp (in seconds) when the interaction completed.
 */
completedAt: number | null,
/**
 * Duration between interaction start and completion in milliseconds, if known.
 */
durationMs: number | null, };
