// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionPlanStep } from "./InteractionPlanStep";

export type InteractionPlanUpdatedNotification = { chatId: string, interactionId: string, explanation: string | null, plan: Array<InteractionPlanStep>, };
