// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { UserInput } from "./UserInput";

export type InteractionStartParams = {chatId: string, clientUserMessageId?: string | null, input: Array<UserInput>, /**
 * Override the working directory for this interaction and subsequent interactions.
 */
cwd?: string | null, /**
 * Override the approval policy for this interaction and subsequent interactions.
 */
approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this interaction and
 * subsequent interactions.
 */
approvalsReviewer?: ApprovalsReviewer | null, /**
 * Override the sandbox policy for this interaction and subsequent interactions.
 */
sandboxPolicy?: SandboxPolicy | null, /**
 * Override the model for this interaction and subsequent interactions.
 */
model?: string | null, /**
 * Override the service tier for this interaction and subsequent interactions.
 */
serviceTier?: string | null | null, /**
 * Override the reasoning effort for this interaction and subsequent interactions.
 */
effort?: ReasoningEffort | null, /**
 * Override the reasoning summary for this interaction and subsequent interactions.
 */
summary?: ReasoningSummary | null, /**
 * Override the personality for this interaction and subsequent interactions.
 */
personality?: Personality | null, /**
 * Optional JSON Schema used to constrain the final assistant message for
 * this interaction.
 */
outputSchema?: JsonValue | null};
