// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification that the interaction-level unified diff has changed.
 * Contains the latest aggregated diff across all file changes in the interaction.
 */
export type InteractionDiffUpdatedNotification = { chatId: string, interactionId: string, diff: string, };
