// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelVerification } from "./ModelVerification";

export type ModelVerificationNotification = { chatId: string, interactionId: string, verifications: Array<ModelVerification>, };
