// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Interaction } from "./Interaction";

export type ReviewStartResponse = { interaction: Interaction,
/**
 * Identifies the thread where the review runs.
 *
 * For inline reviews, this is the original thread id.
 * For detached reviews, this is the id of the new review thread.
 */
reviewChatId: string, };
