// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatGoalStatus } from "./ChatGoalStatus";

export type ChatGoalSetParams = { chatId: string, objective?: string | null, status?: ChatGoalStatus | null, tokenBudget?: number | null, };
