// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationMode } from "../CollaborationMode";
import type { MultiAgentMode } from "../MultiAgentMode";
import type { Personality } from "../Personality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";

export type ChatSettingsUpdateParams = { chatId: string,
/**
 * Override the working directory for subsequent interactions.
 */
cwd?: string | null,
/**
 * Override the approval policy for subsequent interactions.
 */
approvalPolicy?: AskForApproval | null,
/**
 * Override where approval requests are routed for subsequent interactions.
 */
approvalsReviewer?: ApprovalsReviewer | null,
/**
 * Override the sandbox policy for subsequent interactions.
 */
sandboxPolicy?: SandboxPolicy | null,
/**
 * Select a named permissions profile id for subsequent interactions. Cannot be
 * combined with `sandboxPolicy`.
 */
permissions?: string | null,
/**
 * Override the model for subsequent interactions.
 */
model?: string | null,
/**
 * Override the service tier for subsequent interactions. `null` clears the
 * current service tier; omission leaves it unchanged.
 */
serviceTier?: string | null | null,
/**
 * Override the reasoning effort for subsequent interactions.
 */
effort?: ReasoningEffort | null,
/**
 * Override the reasoning summary for subsequent interactions.
 */
summary?: ReasoningSummary | null,
/**
 * EXPERIMENTAL - Set a pre-set collaboration mode for subsequent interactions.
 *
 * For `collaboration_mode.settings.developer_instructions`, `null` means
 * "use the built-in instructions for the selected mode".
 */
collaborationMode?: CollaborationMode | null,
/**
 * @deprecated Ignored. Use `effort: "ultra"` for proactive multi-agent behavior.
 */
multiAgentMode?: MultiAgentMode | null,
/**
 * Override the personality for subsequent interactions.
 */
personality?: Personality | null, };
