// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSettings } from "./ChatSettings";

export type ChatSettingsUpdatedNotification = { chatId: string, chatSettings: ChatSettings, };
