// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { MultiAgentMode } from "../MultiAgentMode";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ActivePermissionProfile } from "./ActivePermissionProfile";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { Chat } from "./Chat";
import type { InteractionsPage } from "./InteractionsPage";
import type { SandboxPolicy } from "./SandboxPolicy";

export type ChatResumeResponse = { chat: Chat, model: string, modelProvider: string, serviceTier: string | null, cwd: AbsolutePathBuf,
/**
 * Chat-scoped runtime workspace roots used to materialize
 * `:workspace_roots`.
 */
runtimeWorkspaceRoots: Array<AbsolutePathBuf>,
/**
 * Environment-native paths to instruction source files currently loaded for this chat.
 */
instructionSources: Array<LegacyAppPathString>, approvalPolicy: AskForApproval,
/**
 * Reviewer currently used for approval requests on this chat.
 */
approvalsReviewer: ApprovalsReviewer,
/**
 * Legacy sandbox policy retained for compatibility. Experimental clients
 * should prefer `activePermissionProfile` for profile provenance.
 */
sandbox: SandboxPolicy,
/**
 * Named or implicit built-in profile that produced the active
 * permissions, when known.
 */
activePermissionProfile: ActivePermissionProfile | null, reasoningEffort: ReasoningEffort | null,
/**
 * @deprecated Always `explicitRequestOnly`. Use `reasoningEffort` for Ultra behavior.
 */
multiAgentMode: MultiAgentMode,
/**
 * `chat/interactions/list` page returned when requested by `initialInteractionsPage`.
 */
initialInteractionsPage: InteractionsPage | null, };
