// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { MultiAgentMode } from "../MultiAgentMode";
import type { Personality } from "../Personality";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { ChatSource } from "./ChatSource";
import type { ChatStartSource } from "./ChatStartSource";
import type { DynamicToolSpec } from "./DynamicToolSpec";
import type { InteractionEnvironmentParams } from "./InteractionEnvironmentParams";
import type { SandboxMode } from "./SandboxMode";
import type { SelectedCapabilityRoot } from "./SelectedCapabilityRoot";

export type ChatStartParams = { model?: string | null, modelProvider?: string | null, serviceTier?: string | null | null, cwd?: string | null,
/**
 * Replace the chat's runtime workspace roots. Paths must be absolute.
 */
runtimeWorkspaceRoots?: Array<AbsolutePathBuf> | null, approvalPolicy?: AskForApproval | null,
/**
 * Override where approval requests are routed for review on this chat
 * and subsequent interactions.
 */
approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null,
/**
 * Named profile id for this chat. Cannot be combined with `sandbox`.
 */
permissions?: string | null, config?: { [key in string]?: JsonValue } | null, serviceName?: string | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null,
/**
 * @deprecated Ignored. Use Ultra reasoning effort for proactive multi-agent behavior.
 */
multiAgentMode?: MultiAgentMode | null, ephemeral?: boolean | null, sessionStartSource?: ChatStartSource | null,
/**
 * Optional client-supplied analytics source classification for this chat.
 */
chatSource?: ChatSource | null,
/**
 * Optional sticky environments for this chat.
 *
 * Omitted selects the default environment when environment access is
 * enabled. Empty disables environment access for interactions that do not
 * provide an interaction override. Non-empty selects the first environment as the
 * current interaction environment.
 */
environments?: Array<InteractionEnvironmentParams> | null, dynamicTools?: Array<DynamicToolSpec> | null,
/**
 * Capability roots selected for this chat by the hosting platform.
 */
selectedCapabilityRoots?: Array<SelectedCapabilityRoot> | null,
/**
 * If true, opt into emitting raw Responses API messages on the event stream.
 * This is for internal use only (e.g. Codex Cloud).
 */
experimentalRawEvents?: boolean, };
