// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `chat/increment_elicitation`.
 */
export type ChatIncrementElicitationResponse = {
/**
 * Current out-of-band elicitation count after the increment.
 */
count: bigint,
/**
 * Whether timeout accounting is paused after applying the increment.
 */
paused: boolean, };
