// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { Personality } from "../Personality";
import type { ResponseItem } from "../ResponseItem";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { ChatResumeInitialInteractionsPageParams } from "./ChatResumeInitialInteractionsPageParams";
import type { SandboxMode } from "./SandboxMode";

/**
 * There are three ways to resume a chat:
 * 1. By chat_id: load the chat from disk by chat_id and resume it.
 * 2. By history: instantiate the chat from memory and resume it.
 * 3. By path: load the chat from disk by path and resume it.
 *
 * For non-running chats, the precedence is: history > non-empty path > chat_id.
 * If using history or a non-empty path for a non-running chat, the chat_id
 * param will be ignored.
 *
 * If chat_id identifies a running chat, app-server rejoins that chat and
 * treats a non-empty path as a consistency check against the active rollout path.
 * Empty string path values are treated as absent.
 *
 * Prefer using chat_id whenever possible.
 */
export type ChatResumeParams = { chatId: string,
/**
 * [UNSTABLE] FOR CODEX CLOUD - DO NOT USE.
 * If specified, the chat will be resumed with the provided history
 * instead of loaded from disk.
 */
history?: Array<ResponseItem> | null,
/**
 * [UNSTABLE] Specify the rollout path to resume from.
 * If specified for a non-running chat, the chat_id param will be ignored.
 * If chat_id identifies a running chat, the path must match the active
 * rollout path.
 */
path?: string | null,
/**
 * Configuration overrides for the resumed chat, if any.
 */
model?: string | null, modelProvider?: string | null, serviceTier?: string | null | null, cwd?: string | null,
/**
 * Replace the chat's runtime workspace roots. Paths must be absolute.
 */
runtimeWorkspaceRoots?: Array<AbsolutePathBuf> | null, approvalPolicy?: AskForApproval | null,
/**
 * Override where approval requests are routed for review on this chat
 * and subsequent interactions.
 */
approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null,
/**
 * Named profile id for the resumed chat. Cannot be combined with
 * `sandbox`.
 */
permissions?: string | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null,
/**
 * When true, return only chat metadata and live-resume state without
 * populating `chat.interactions`. This is useful when the client plans to call
 * `chat/interactions/list` immediately after resuming.
 */
excludeInteractions?: boolean,
/**
 * When present, include a `chat/interactions/list` page in the resume response
 * so clients can bootstrap recent interactions without a second request.
 */
initialInteractionsPage?: ChatResumeInitialInteractionsPageParams | null, };
