// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "./Chat";

export type ChatRollbackResponse = {
/**
 * The updated chat after applying the rollback, with `interactions` populated.
 *
 * The messages stored in each interaction are lossy since we explicitly do not
 * persist all agent interactions, such as command executions. This is the same
 * behavior as `chat/resume`.
 */
chat: Chat, };
