// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatBackgroundTerminal } from "./ChatBackgroundTerminal";

export type ChatBackgroundTerminalsListResponse = { data: Array<ChatBackgroundTerminal>,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more messages to return.
 */
nextCursor: string | null, };
