// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionMessagesView } from "./InteractionMessagesView";
import type { SortDirection } from "./SortDirection";

export type ChatInteractionsListParams = { chatId: string,
/**
 * Opaque cursor to pass to the next call to continue after the last interaction.
 */
cursor?: string | null,
/**
 * Optional interaction page size.
 */
limit?: number | null,
/**
 * Optional interaction pagination direction; defaults to descending.
 */
sortDirection?: SortDirection | null,
/**
 * How much message detail to include for each returned interaction; defaults to summary.
 */
messagesView?: InteractionMessagesView | null, };
