// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSortKey } from "./ChatSortKey";
import type { ChatSourceKind } from "./ChatSourceKind";
import type { SortDirection } from "./SortDirection";

export type ChatSearchParams = {
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null,
/**
 * Optional sort key; defaults to created_at.
 */
sortKey?: ChatSortKey | null,
/**
 * Optional sort direction; defaults to descending (newest first).
 */
sortDirection?: SortDirection | null,
/**
 * Optional source filter; when set, only sessions from these source kinds
 * are returned. When omitted or empty, defaults to interactive sources.
 */
sourceKinds?: Array<ChatSourceKind> | null,
/**
 * Optional archived filter; when set to true, only archived chats are returned.
 * If false or null, only non-archived chats are returned.
 */
archived?: boolean | null,
/**
 * Required substring/full-text query for chat search.
 */
searchTerm: string, };
