// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { ChatSource } from "./ChatSource";
import type { SandboxMode } from "./SandboxMode";

/**
 * There are two ways to fork a chat:
 * 1. By chat_id: load the chat from disk by chat_id and fork it into a new chat.
 * 2. By path: load the chat from disk by path and fork it into a new chat.
 *
 * If using a non-empty path, the chat_id param will be ignored.
 * Empty string path values are treated as absent.
 *
 * Prefer using chat_id whenever possible.
 */
export type ChatForkParams = { chatId: string,
/**
 * [UNSTABLE] Specify the rollout path to fork from.
 * If specified, the chat_id param will be ignored.
 */
path?: string | null,
/**
 * Configuration overrides for the forked chat, if any.
 */
model?: string | null, modelProvider?: string | null, serviceTier?: string | null | null, cwd?: string | null,
/**
 * Replace the chat's runtime workspace roots. Paths must be absolute.
 */
runtimeWorkspaceRoots?: Array<AbsolutePathBuf> | null, approvalPolicy?: AskForApproval | null,
/**
 * Override where approval requests are routed for review on this chat
 * and subsequent interactions.
 */
approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null,
/**
 * Named profile id for the forked chat. Cannot be combined with
 * `sandbox`.
 */
permissions?: string | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, ephemeral?: boolean,
/**
 * Optional client-supplied analytics source classification for this forked chat.
 */
chatSource?: ChatSource | null,
/**
 * When true, return only chat metadata and live fork state without
 * populating `chat.interactions`. This is useful when the client plans to call
 * `chat/interactions/list` immediately after forking.
 */
excludeInteractions?: boolean, };
