// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSearchResult } from "./ChatSearchResult";

export type ChatSearchResponse = { data: Array<ChatSearchResult>,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * if None, there are no more messages to return.
 */
nextCursor: string | null,
/**
 * Opaque cursor to pass as `cursor` when reversing `sortDirection`.
 * This is only populated when the page contains at least one chat.
 * Use it with the opposite `sortDirection`; for timestamp sorts it anchors
 * at the start of the page timestamp so same-second updates are not skipped.
 */
backwardsCursor: string | null, };
