// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRealtimeAudioChunk } from "./ChatRealtimeAudioChunk";

/**
 * EXPERIMENTAL - append audio input to thread realtime.
 */
export type ChatRealtimeAppendAudioParams = { chatId: string, audio: ChatRealtimeAudioChunk, };
