// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for `chat/increment_elicitation`.
 */
export type ChatIncrementElicitationParams = {
/**
 * Chat whose out-of-band elicitation counter should be incremented.
 */
chatId: string, };
