// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatGoal } from "./ChatGoal";

export type ChatGoalUpdatedNotification = { chatId: string, interactionId: string | null, goal: ChatGoal, };
