// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileUpdateChange } from "./FileUpdateChange";

export type FileChangePatchUpdatedNotification = { chatId: string, interactionId: string, messageId: string, changes: Array<FileUpdateChange>, };
