-- The dedicated logs schema is Datax-native from its defining migrations.
-- Version 3 remains as a migration marker so databases and tests keep the same
-- migration timeline after `thread_id` was mechanically folded into `chat_id`
-- in earlier logs migrations.
